application: hackerfeedbackend
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Endpoints Handler
- url: /_ah/spi/.*
  script: main.application

libraries:
- name: endpoints
  version: 1.0